### ISSUE TITLE
Tags page looks weird on mobile

### ISSUE THREAD

**Issue by ViddeM** [ViddeM/vrecipes#107]
The tags table page looks weird on mobile on first load, fixes itself when the user touches the screen.

![image](https://user-images.githubusercontent.com/16452604/175382195-11480a02-0bc1-495e-816a-d74127eb9831.jpeg)

**Comment by ericlp** [comment]
Can't reproduce

**Comment by ViddeM** [comment]
Solved with 6b102046f4f6dfa1ba534482a3418dc7006cb327
