### ISSUE TITLE
Add possibility of headings for ingredients and recipe-steps

### ISSUE THREAD

**Issue by ViddeM** [ViddeM/vrecipes#85]
The user should be able to add headings for ingredients / steps to better structure the recipe.

An example could be that one would want to split ingredients for the ''filling'' and the ''dough'' for a cake.

**Comment by ericlp** [comment]
Didn't you solve this?

**Comment by ViddeM** [comment]
Not yet :/

**Comment by ViddeM** [comment]
It is solved now tho xd
